2022-03-18 18:38:01 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.sec.gov/Archives/edgar/data/860518/000114420416128738/0001144204-16-128738-index.htm> (referer: https://www.sec.gov/)
Traceback (most recent call last):
  File "C:\Users\Xu\AppData\Local\Programs\Python\Python310\lib\site-packages\twisted\internet\defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "C:\Users\Xu\Desktop\sec_scraper\sec\sec\spiders\sec.py", line 55, in filing_detail
    link = tr.split('<a href="/ix?doc=')[1].split('">')[0]
IndexError: list index out of range
2022-03-18 19:18:20 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.sec.gov/Archives/edgar/data/40730/000119312520159505/0001193125-20-159505-index.htm> (referer: https://www.sec.gov/)
Traceback (most recent call last):
  File "C:\Users\Xu\AppData\Local\Programs\Python\Python310\lib\site-packages\twisted\internet\defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "C:\Users\Xu\Desktop\sec_scraper\sec\sec\spiders\sec.py", line 55, in filing_detail
    link = tr.split('<a href="/ix?doc=')[1].split('">')[0]
IndexError: list index out of range
2022-03-18 19:18:20 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.sec.gov/Archives/edgar/data/1012569/000101256917000022/0001012569-17-000022-index.htm> (referer: https://www.sec.gov/)
Traceback (most recent call last):
  File "C:\Users\Xu\AppData\Local\Programs\Python\Python310\lib\site-packages\twisted\internet\defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "C:\Users\Xu\Desktop\sec_scraper\sec\sec\spiders\sec.py", line 55, in filing_detail
    link = tr.split('<a href="/ix?doc=')[1].split('">')[0]
IndexError: list index out of range
2022-03-18 20:30:03 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.sec.gov/Archives/edgar/data/1434110/000114420419019899/0001144204-19-019899-index.htm> (referer: https://www.sec.gov/)
Traceback (most recent call last):
  File "C:\Users\Xu\AppData\Local\Programs\Python\Python310\lib\site-packages\twisted\internet\defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "C:\Users\Xu\Desktop\sec_scraper\sec\sec\spiders\sec.py", line 55, in filing_detail
    link = tr.split('<a href="/ix?doc=')[1].split('">')[0]
IndexError: list index out of range
